# Generated by Django 3.1.7 on 2021-02-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_customtext_target_chipid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtext',
            name='target_chipid',
            field=models.IntegerField(default=1423642132),
        ),
    ]
