# Generated by Django 3.1.7 on 2021-02-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20210222_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtext',
            name='target_chipid',
            field=models.IntegerField(default=56990860413),
        ),
    ]
