# Generated by Django 3.1.7 on 2021-02-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_auto_20210222_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtext',
            name='target_chipid',
            field=models.IntegerField(default=96335863300),
        ),
    ]
