# Generated by Django 3.1.7 on 2021-06-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_auto_20210222_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='created_by',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='customtext',
            name='target_chipid',
            field=models.IntegerField(default=367709173),
        ),
    ]
